name: CI-CD pipeline

on:
  workflow_dispatch: 
    inputs:
      environment: 
        type: choice
        description: "Environment in which deployment needs to be done"
        required: true
        options:
        - DEV
        - QA
        - PROD
    
#ENV: ${{ github.event.inputs.environment }}

jobs:
  test_job:
    runs_on: ubuntu_latest
    steps:
    - run: echo ${{ github.event.inputs.environment }}
